### ISSUE TITLE
[feature] self-identifying parameters in map forms

### ISSUE THREAD

**Issue by mathieucaroff** [ditrit/lidy#3]
The OSASIS Tosca lidy schema has the following type:

```yaml
topology_template::TTopologyTemplate:
  _mapFacultative:
    description: description
    inputs: input_parameters
    outputs: output_parameters
    node_templates: node_templates
    relationship_templates: relationship_templates
    groups: group_defs
    policies: policy_defs
    substitution_mappings: substitution_mappings
    workflows: imperative_workflow_defs
```

There are a few repetitions of identifiers between keys and values: `description: description`. Since `_*` are reserved by lidy, we could use `_` as a special value to indicate that the value of the entry should be checked by the rule whose name corresponds to the key. This would allow to write the above schema as follows:

```yaml
topology_template::TTopologyTemplate:
  _mapFacultative:
    description: _
    inputs: input_parameters
    outputs: output_parameters
    node_templates: _
    relationship_templates: relationship_templates
    groups: group_defs
    policies: policy_defs
    substitution_mappings: _
    workflows: imperative_workflow_defs
```

@treivax Does it look good to you?

**Comment by mathieucaroff** [comment]
I just came across a similar use case: *namespaced* self-identifying parameters.

I believe that namespaced self-identifying parameters will the more common use case of the two, so the syntax for SIP (self-identifying parameters) should take it into account.

Example:

```yaml
value_expression::TValueExpression:
  _max: 1
  _mapFacultative:
    concat:               value_expression.concat
    get_input:            value_expression.get_input
    get_nodes_of_type:    value_expression.get_nodes_of_type
    token:                value_expression.token
    join:                 value_expression.join
    get_property:         value_expression.get_property
    get_attribute:        value_expression.get_attribute
    get_operation_output: value_expression.get_operation_output
    get_artifact:         value_expression.get_artifact
```

The above lidy rule would then become:

```yaml
value_expression::TValueExpression:
  _max: 1
  _mapFacultative:
    concat: _
    get_input: _
    get_nodes_of_type: _
    token: _
    join: _
    get_property: _
    get_attribute: _
    get_operation_output: _
    get_artifact: _
```
